### ISSUE TITLE
Can't get payments to work

### ISSUE THREAD

**Issue by ekerstein** [biscottigelato/SwiftLightning#12]
Every time I scan a QR code the to/amount/description fill as they should. But when I try to pay I get "rpc error: code = Unknown desc = target not found".

I've already tried restarting app and also re-installing app.

**Comment by biscottigelato** [comment]
I am taking it that you already have a channel created? Routing predictability is still a problem and it's kinda out of my hands. Trying to give better visibility to the user regarding routing in the next release tho.
