### ISSUE TITLE
"Lightning:" uri prefix

### ISSUE THREAD

**Issue by ekerstein** [biscottigelato/SwiftLightning#13]
Please make sure the QR code scanner accepts both capitalized / uncapitalized prefixes of "Lightning:", or perhaps is just case insensitive. There was a discussion in Slack where Yalls QR codes became unreadable because Alex capitalized the prefix.

It worked fine on Shango, so it seems specific to this app.

**Comment by biscottigelato** [comment]
This should now be fixed. Please confirm. Thanks
