### ISSUE TITLE
SLSeedField should probably not have correction enabled (?)

### ISSUE THREAD

**Issue by heumn** [biscottigelato/SwiftLightning#16]
![skjermbilde 2018-07-08 kl 18 52 07](https://user-images.githubusercontent.com/1769314/42422511-d20c44f6-82e7-11e8-93ff-dc0cc99c167d.png)

I will gladly fix this as a simple starter task :)

**Comment by biscottigelato** [comment]
Yeah. That'd be awesome. Thanks! :)
