### ISSUE TITLE
Reconverting LND .proto files into Swift

### ISSUE THREAD

**Issue by lllovesmatt** [biscottigelato/SwiftLightning#17]
Followed the documentation on reconverting LND .proto files into Swift, but got errors related between the old+new `rpc.grpc.swift` files.

_Not sure if it is something wrong in my setup, or if its an actual issue._

#### Steps to reproduce:
[x] Install Swift Protobuf
[x] Install Swift GRPC
[x] LND in GOPATH for script to work

#### Diff + errors sample screenshot:

<img width="1277" alt="screen shot 2018-07-09 at 8 50 38 pm" src="https://user-images.githubusercontent.com/6657488/42532731-6dcd39ac-844d-11e8-80d0-9a83a80dc63f.png">

**Comment by biscottigelato** [comment]
I just gave the script a try again against some random newer version of lnd. It merely added a few dozens more definitions into rpc.grpc.swift and rpc.pb.swift. No incompatibilities with the Xcode project even if I do a clean + build.

Can you do a diff of what you got generated against what's in the repository and try to debug it that way? Thanks!

**Comment by lllovesmatt** [comment]
Thanks for taking questions on this, I think its finally figured out, so I updated the README and made a PR: [Update README with swift-grpc tag #21 ](https://github.com/biscottigelato/SwiftLightning/pull/21)

Let me know if any questions-
