### ISSUE TITLE
Commit pods to repo

### ISSUE THREAD

**Issue by heumn** [biscottigelato/SwiftLightning#19]
Pros and cons mentioned here:

Thoughts?
https://github.com/biscottigelato/SwiftLightning/pull/18

I always like having them in the project. Makes for a more stable environment and easier first time setup

**Comment by biscottigelato** [comment]
Yeah, I have always been at a toss between having them vs not. I am not strongly into one side or another. If your experience is that it'll help onboard new comers, I'm open to have them committed.

**Comment by biscottigelato** [comment]
If so, do you think you can do the commit? I am thinking you probably have newer versions of the Pods than I do at this point, and that you were able to give them a test. Thx!
