### ISSUE TITLE
Problems building Lndmobile.framework 

### ISSUE THREAD

**Issue by sergioabril** [biscottigelato/SwiftLightning#24]
First, let me say I love this; I really hope this helps increase Lightning adoption. 

I'm trying to build **Lndmobile.framework**, but I'm failing. I'm sure it's an easy one, because it's the first time I work with go... But I can't get it right.

Whenever I run `./build_mobile.sh ` after `dep ensure`, I get this:

```
mobile sergio$ ./build_mobile.sh
current dir is /Users/sergio/go/src/github.com/lightningnetwork/lnd/mobile
Generating mobile bindings (api_generated.go).
Done.
Building for iOS (/Users/sergio/go/src/github.com/lightningnetwork/lnd/mobile/build/ios/Lndmobile.framework)...
runtime/cgo
os/user
golang.org/x/mobile/internal/mobileinit
net
gobind
runtime/cgo
os/user
golang.org/x/mobile/internal/mobileinit
net
gobind
runtime/cgo
golang.org/x/mobile/internal/mobileinit
os/user
net
gobind
runtime/cgo
golang.org/x/mobile/internal/mobileinit
os/user
net
gobind
gobind
github.com/lightningnetwork/lnd/vendor/golang.org/x/crypto/blake2b.supportsAVX2: relocation target runtime.support_avx2 not defined
github.com/lightningnetwork/lnd/vendor/golang.org/x/crypto/blake2b.supportsAVX: relocation target runtime.support_avx not defined
/Users/sergio/go/bin/gomobile: darwin-amd64: go build -tags ios ios -v -buildmode=c-archive -o /var/folders/3m/lw75tc4j01l23nj0flcgpr800000gn/T/gomobile-work-195040768/lndmobile-amd64.a gobind failed: exit status 2

```

I'm on branch `mobile-tip` (I've tried with `mobile-dev`, and it throws even more errors)

Any tip would be appreciated, Thanks!

**Comment by biscottigelato** [comment]
Hi! Thanks for your interest in the project!

I think I did try to fall back to mobile_tip (aka. 0.4.2) and it no longer works. If you don't mind to give mobile_dev branch a try again. I just checked-in a quick fix and it should build.

That said I find 0.5.0 having problems in getting headers and finding nodes... Which makes Lightning operations very unreliable. So YMMV. Would love to see if you have better luck than I do.

**Comment by sergioabril** [comment]
Sure! I just tried to build it using mobile_dev after pulling the last commit, and it worked like a charm. I saw that you commented the DebugBuild part (which was the error I was getting). Yay!

Regarding 0.5.0, sad to hear that. This is my first contact with Lnd in general, so I'm still learning, but let's see what I can do. Thank you so much!
