### ISSUE TITLE
Issue running ./lnd/mobile/build_mobile.sh

### ISSUE THREAD

**Issue by s3ton** [biscottigelato/SwiftLightning#6]
Hi,
I have a similar issue.
After successfully running dep ensure I run:

```
$ ./lnd/mobile/build_mobile.sh
current dir is /Users/user/go/src/github.com/lightningnetwork/lnd/mobile
Generating mobile bindings (api_generated.go).
./gen_bindings.sh: line 4: protoc: command not found
bindings.go:13: running "./gen_bindings.sh": exit status 127
```

Any idea?

**Comment by biscottigelato** [comment]
Ah... I forgot to mention that you'd also need Gomobile and Protoc (Google's Protocol Buffer Compiler) for this. I updated to Readme to reflect this. Installing Protoc is a little bit of a hoop jump too, but I don't think I can provide instructions any better than Google can. So I simply added a link in Readme in hope that it won't be too complicated. Please give it a try if you can. Thanks!

**Comment by s3ton** [comment]
Ok I was able to complete the process now. 
For protobuf I found some very easy to follow instructions [here](https://medium.com/@erika_dike/installing-the-protobuf-compiler-on-a-mac-a0d397af46b8).
